### ISSUE TITLE
Feature Request: Don't remove img until svg is rendered

### ISSUE THREAD

**Issue by weotch** [iconic/SVGInjector#21]
There is a flicker between when SVGInejctor runs and removes the `img` tag and before the `svg` appears.  I think the `img` should only be removed once the `svg` is ready so the cutover is transparent.  Or maybe this is an option the dev can opt into.

**Comment by SachaG** [comment]
The `data-src` solution works, but there's a flicker where you still see the broken image borders. So I ended up using the second solution as well. 

It does seem like @weotch's idea of having both the image and SVG present in the DOM at the same time might work better, although it's probably a bit trickier to implement.
