### ISSUE TITLE
Safari .cloneNode() fails

### ISSUE THREAD

**Issue by timkendall** [iconic/SVGInjector#25]
Doesn't work in Safari, this snippet throws an error 
```javascript
var cloneSvg = function (sourceSvg) {
    return sourceSvg.cloneNode(true);
};
```

**Comment by protodave** [comment]
Hi Tim! What version of Safari are you using to test? And what error is being thrown?

Not sure if it's related to the issue you are seeing, but older versions of WebKit didn't have `cloneNode()` implemented for SVG elements (but support was added back in 2010):
https://bugs.webkit.org/show_bug.cgi?id=41421

**Comment by timkendall** [comment]
Version 8.0.2 getting `TypeError: undefined is not a function (evaluating 'sourceSvg.cloneNode('true')'`

**Comment by timkendall** [comment]
Thought it was weird that it wouldn't work in Safari, may just be something I'm doing wrong.
