### ISSUE TITLE
Safari 9.0.2. fails over cloneNode

### ISSUE THREAD

**Issue by hans2103** [iconic/SVGInjector#39]
using SVGinjector 1.1.3 on [Amref.nl](https://www.amref.nl) and I receive a javascript error on Safari 9.0.2 

```
[Error] TypeError: sourceSvg.cloneNode is not a function. (In 'sourceSvg.cloneNode(true)', 'sourceSvg.cloneNode' is undefined)
    cloneSvg
    (anonieme functie)
```

This results in not showing both img nor svg on Safari.
I have no issue on Chrome nor Firefox. 

(this issue looks a lot like #25 but I can't see any solution in it)

**Comment by hans2103** [comment]
found something... it's conflicting with mootools. 
Without mootools there is no fail.
With mootools enabled (used by some extensions on this website) there is a fail on Safari.

**Comment by hans2103** [comment]
- install plugin Mootools Enable/Disable
- configuratie = mootools standaard UIT
- mod_finder
- configuratie = geen autocomplete

Met deze settings gaat het goed en wordt het logo op Safari netjes getoond. 
Ik heb bij de makers van het svg script een issue aangemaakt met verzoek er naar te kijken: https://github.com/iconic/SVGInjector/issues/39

Het uitschakelen van AutoComplete is wat mij betreft tijdelijk. Het tonen van logo leek mij namelijk belangrijker dan de aanwezigheid van AutoComplete. 

wordt vervolgd

**Comment by varyen** [comment]
I can confirm this, fails on website with mootools with same error
