### ISSUE TITLE
Is this No Longer Maintained?

### ISSUE THREAD

**Issue by ghost** [iconic/SVGInjector#52]
Hi @protodave and other contributors.

First off, amazing work! This lib has been very helpful for developing without needing to manage inline SVG in source code.

It seems there are [11 pull requests](https://github.com/iconic/SVGInjector/pulls) open, with the oldest one dating back to 2014. Is this lib no longer being maintained?

I want to submit a PR to allow attributes like `onClick`, but am afraid that the PR will just sit like the others open.

> "Is anybody out there listening?"

**Comment by joelkesler** [comment]
+1

**Comment by Viveur** [comment]
Looking at the forks list it would appear that Florian Bacher is currently leading development of SVG Injector v2. 

It is directly installable via bower/npm and he is regularly merging in new code.

https://github.com/flobacher/SVGInjector2

**Comment by joelkesler** [comment]
Thanks for the update @TheCopartnery

**Comment by ghost** [comment]
Thank you @TheCopartnery. Going to close this
